on:
  push:
    branches:
      - jameson_alpha
  pull_request:
    branches:
      - jameson_alpha
  workflow_dispatch:

name: test-only

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R:
          - '4.0.2'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev

      - name: Install dependencies from GitHub
        run: |
          Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
          Rscript -e "remotes::install_github('gUtils', upgrade = 'never')"
          Rscript -e "remotes::install_github('gChain', upgrade = 'never')"
          Rscript -e "remotes::install_version('Matrix', upgrade = 'never')"
          Rscript -e "remotes::install_version('igraph', version = '1.3.0', upgrade = 'never')"
          Rscript -e "remotes::install_version('magrittr', upgrade = 'never')"
          Rscript -e "remotes::install_version('pbmcapply', upgrade = 'never')"
          Rscript -e "remotes::install_version('GenomicRanges', upgrade = 'never')"
          Rscript -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager')"
          Rscript -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg38', version = '3.12', ask = FALSE)"
          Rscript -e "remotes::install_version('zoo', upgrade = 'never')"
          Rscript -e "remotes::install_version('R6', upgrade = 'never')"
          Rscript -e "remotes::install_version('plyr', upgrade = 'never')"
          Rscript -e "remotes::install_version('arrow', upgrade = 'never')"
          Rscript -e "remotes::install_version('stats', upgrade = 'never')"
          Rscript -e "remotes::install_version('MASS', upgrade = 'never')"

      - name: Run tests
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual
        shell: bash
