on:
  push:
    branches:
      - jameson_alpha
  pull_request:
    branches:
      - jameson_alpha
  workflow_dispatch:

name: test-only

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        R:
          - '4.0.2'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: covr


      - name: Install system dependencies
        run: |
          brew install glpk
          brew install harfbuzz
          brew install fribidi

      - name: Install remote dependencies
        run: |
          Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
          Rscript -e "remotes::install_version('textshaping', upgrade = 'never')"
          Rscript -e "remotes::install_version('ragg', upgrade = 'never')"
          Rscript -e "remotes::install_version('pkgdown', upgrade = 'never')"
          Rscript -e "install.packages('devtools')"
          Rscript -e "remotes::install_version('Matrix', upgrade = 'never')"
          Rscript -e "remotes::install_version('igraph', version = '1.3.0', upgrade = 'never')"
          Rscript -e "remotes::install_version('magrittr', upgrade = 'never')"
          Rscript -e "remotes::install_version('pbmcapply', upgrade = 'never')"
          Rscript -e "remotes::install_version('zoo', upgrade = 'never')"
          Rscript -e "remotes::install_version('R6', upgrade = 'never')"
          Rscript -e "remotes::install_version('plyr', upgrade = 'never')"
          Rscript -e "remotes::install_version('arrow', upgrade = 'never')"

      - name: Install Bioconductor packages
        run: |
          Rscript -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager')"
          Rscript -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg38', version = '3.12', ask = FALSE)"
          Rscript -e "BiocManager::install('GenomicRanges', version = '3.12')"

      - name: Install dependencies from GitHub
        run: |
          Rscript -e "remotes::install_github('mskilab-org/gUtils', upgrade = 'never')"
          Rscript -e "remotes::install_github('mskilab-org/gChain', upgrade = 'never')"

      - name: Run tests
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual
        shell: bash
        
      - name: Test coverage
        run: covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))
        shell: Rscript {0}
